version: '3.8'
services:
  app:
    container_name: app-core-shorten
    image: nhan2804/app-core:shorten-v1.0.0
    pull_policy: if_not_present
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: 'node dist/main.js'
    ports:
      - 5000:5001

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
volumes:
  rabbitmq_data:
